{
 "title": "Wazuh-Firewall Dashboard",
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "10s",
 "panels": [
  { "title": "Wazuh SIEM", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Low Alerts",
   "type": "gauge",
   "description": "Rule Level 0 TO 3",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[0 TO 3]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Medium Alerts",
   "type": "gauge",
   "description": "Rule Level 4 TO 7",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[4 TO 7]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "High Alerts",
   "type": "gauge",
   "description": "Rule Level 8 TO 15",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[8 TO 15]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Total Alerts",
   "type": "stat",
   "gridPos": { "h": 7, "w": 4, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "id": "2",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Alerts over time",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "alias": "Low Alerts",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[0 TO 3]",
     "timeField": "timestamp"
    },
    {
     "alias": "Medium Alerts",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[4 TO 6]",
     "timeField": "timestamp"
    },
    {
     "alias": "High Alerts",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[7 TO 15]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "High/Critical Alerts ",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 0, "y": 8 },
   "targets": [
    {
     "alias": "High Alerts",
     "bucketAggs": [
      {
       "field": "timestamp",
       "id": "4",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_level:[7 TO 15]",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Agents with Alerts",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 13, "x": 11, "y": 8 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "agent_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Rules (by alerts)",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 9, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_description",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top MITRE ATT&CK / Techniques  Types",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 9, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_mitre_technique",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_mitre_technique:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top Rule Groups",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "rule_groups",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Authentication Success vs Failure",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 24 },
   "targets": [
    {
     "alias": "Success",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*authentication_success*",
     "timeField": "timestamp"
    },
    {
     "alias": "Failure",
     "bucketAggs": [
      { "field": "timestamp", "id": "2", "settings": { "interval": "auto" }, "type": "date_histogram" }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "rule_groups:*authentication_failed*\n",
     "timeField": "timestamp"
    }
   ]
  },
  { "title": "Firewall (FW)", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 } },
  {
   "title": "Traffic Blocked vs Allowed",
   "type": "piechart",
   "description": "Distribution of firewall actions",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "action",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Blocked Traffic by Country",
   "type": "geomap",
   "gridPos": { "h": 15, "w": 11, "x": 7, "y": 33 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DestinationIP_country_code",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "utc", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense\n\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Blocked Destination Ports",
   "type": "piechart",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 33 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "dst-port",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      },
      {
       "field": "timestamp",
       "id": "3",
       "settings": { "interval": "auto", "min_doc_count": "0", "timeZone": "Asia/Karachi", "trimEdges": "0" },
       "type": "date_histogram"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense AND action:block",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Traffic by Protocol",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 7, "x": 0, "y": 40 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "protocol-name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "_term", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Blocked Destination IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 6, "x": 18, "y": 40 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DestinationIP",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense AND action:block AND interface:vtnet1",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Top 10 Blocked Source IPs",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 48 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "src_ip",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "10" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense AND action:block AND interface:vtnet0\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Blocked Countries",
   "type": "barchart",
   "gridPos": { "h": 8, "w": 9, "x": 8, "y": 48 },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DestinationIP_country_code",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense AND action:block\n",
     "timeField": "timestamp"
    }
   ]
  },
  {
   "title": "Blocked Cities",
   "type": "stat",
   "gridPos": { "h": 8, "w": 7, "x": 17, "y": 48 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "bucketAggs": [
      {
       "field": "DestinationIP_city_name",
       "id": "2",
       "settings": { "min_doc_count": "1", "order": "desc", "orderBy": "1", "size": "0" },
       "type": "terms"
      }
     ],
     "metrics": [
      { "id": "1", "type": "count" }
     ],
     "query": "log_type:opnsense AND action:block\n",
     "timeField": "timestamp"
    }
   ]
  }
 ]
}